[window]
title = "Alacritty"
dynamic_title = false
[scrolling]
history = 100000
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "SemiBoldItalic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "BoldItalic" }
size = 10
offset = { x = 1, y = 0 }
[mouse]
hide_when_typing = true
[cursor]
style = { blinking = "Always" }
blink_interval = 450
blink_timeout = 0
[terminal]
shell = "pwsh.exe"
[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Return", mode = "Vi", action = "ToggleViMode" },
]
